Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2019-10, with the labels that each got.

#467 ROC-6130: Inversion of Control for legal representatives frontend
  charts/cmc-legal-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/dockertests.json
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/app/claims/claimStoreClient.ts
Labels: ns:cmc-legal-frontend-pr-467

#468 Added new accessibility statement page
  src/main/app/paths.ts
  src/main/routes/accessibility-statement.ts
  src/main/views/accessibility-statement.njk
  src/main/views/includes/support-links.njk
  src/test/routes/acessibility-statement.ts
Labels: ns:cmc-legal-frontend-pr-468

#477 ROC-6132: Turn IOC on for legal rep on AAT
  infrastructure/aat.tfvars
Labels: ns:cmc-legal-frontend-pr-477

#478 ROC-6132: Turn IOC on for legal rep on PROD
  infrastructure/prod.tfvars
Labels: ns:cmc-legal-frontend-pr-478
