Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2019-02, with the labels that each got.

#413 Activate ACR build, image multistaging and hmcts runtime user
  .dockerignore
  .gitignore
  Dockerfile
  acb.tpl.yaml
Labels: ns:cmc-legal-frontend-pr-413

#415 Update docker-compose image to match integration-tests
  docker-compose.local.yml
  docker-compose.yml
Labels: ns:cmc-legal-frontend-pr-415

#416 Remove hmcts user as it will be the default user
  Dockerfile
Labels: docker-optimisation, ns:cmc-legal-frontend-pr-416

#419 set up cmc legal rep security scan
  Jenkinsfile_nightly
  security.sh
Labels: ns:cmc-legal-frontend-pr-419

#422 Change title of claim details page
  src/main/features/dashboard/views/claim-details.njk
Labels: ns:cmc-legal-frontend-pr-422

#421 Fix nightly Jenkins security scanning
  Jenkinsfile_nightly
Labels: ns:cmc-legal-frontend-pr-421

#420 Fix git push to demo
  Jenkinsfile_CNP
Labels: ns:cmc-legal-frontend-pr-420

#424 Exclude the acb.yaml file from being ignored on acr build
  .dockerignore
Labels: ns:cmc-legal-frontend-pr-424
