Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2020-11, with the labels that each got.

#903 Test case failure fix
  src/integration-test/tests/legal/amountClaim/enterAmountClaimDetails_test.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-903

#899 updated audit.json
  audit.json
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-899

#917 Bug fix : Payment failure
  src/main/app/pay/model/paymentResponse.ts
  src/test/http-mocks/pay.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-917

#933 Update package.json
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-933
