Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2020-09, with the labels that each got.

#801 ROC-8211-Legal-rep-nightly-build-failure-fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-801

#823 Nightly dev
  Jenkinsfile_nightly
  bin/run-nightly-tests.sh
  default.conf.js
  docker-compose.nightly-functional-tests.yml
  package.json
  saucelabs.conf.js
  src/integration-test/helpers/saucelabsReporter.js
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-823

#819 Fixing integration tests: ROC-8257
  Jenkinsfile_nightly
  bin/run-nightly-tests.sh
  default.conf.js
  docker-compose.nightly-functional-tests.yml
  package.json
  saucelabs.conf.js
  src/integration-test/data/legal-test-data.ts
  src/integration-test/helpers/downloadPdfHelper.ts
  src/integration-test/helpers/pageHelper.js
  src/integration-test/helpers/saucelabsReporter.js
  src/integration-test/tests/legal/amountClaim/enterAmountClaimDetails_smoke_test.ts
  src/integration-test/tests/legal/amountClaim/enterAmountClaimDetails_test.ts
  src/integration-test/tests/legal/amountClaim/pages/submitted.ts
  src/integration-test/tests/legal/amountClaim/steps/amountClaims.ts
  src/integration-test/tests/legal/claim/enterClaimantDetails_test.ts
  src/integration-test/tests/legal/defence/enterDefendantDetails_test.ts
  src/main/features/certificateOfService/views/document-upload.njk
  src/main/features/claim/views/preferred-court.njk
  src/main/features/dashboard/views/claim-details.njk
  src/main/views/accessibility-statement.njk
  src/main/views/includes/phase_banner_beta.njk
  src/main/views/includes/service_survey_link.njk
  src/main/views/includes/support-links.njk
  types/steps-override.d.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-819

#815 feature(ROC-8262): Configure zap-cli to only error for Medium and above alerts in nightly security scan
  Jenkinsfile_nightly
  audit.json
  package.json
  security.sh
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-815

#832 fix release pipeline
  docker-compose.functional-tests.yml
  package.json
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-832

#835 fix: add changes made to other functional test compose files (release…
  docker-compose.smoke-tests.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-835
