Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2020-03, with the labels that each got.

#667 Switch to AKS on prod
  Jenkinsfile_CNP
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-667

#670 ROC-7648 Do not cache dynamic files
  src/main/modules/helmet/index.ts
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-670

#682 decommission ase aat
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-682

#685 decommission ase prod
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-685

#671 Align the PR template with the citizen-frontend
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-671
