Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2020-04, with the labels that each got.

#697 remove terraform ase from code base
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-697

#699 remove core-infras
  infrastructure/state.tf
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-699

#714 upgrade nodejs chart version
  charts/cmc-legal-frontend/Chart.yaml
  charts/cmc-legal-frontend/requirements.yaml
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-714

#720 ROC-7857-SOT change for Legal Rep Journey
  src/main/features/claim/views/statement-of-truth.njk
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-720

#733 update config for jenkins
  Jenkinsfile_CNP
  docker-compose.yml
Labels: ns:money-claims, rel:cmc-legal-frontend-pr-733
