Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2021-01, with the labels that each got.

#969 Bot/master pr
  .nvmrc
  infrastructure/.terraform-version
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-969

#974 fix security vulnerability
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-974

#918 Sonar issue : Code smell fix
  src/main/app/claims/claimModelConverter.ts
  src/main/app/forms/models/claimantDetails.ts
  src/main/app/forms/models/cookie.ts
  src/main/app/forms/models/defendantDetails.ts
  src/main/app/forms/models/fileTypes.ts
  src/main/common/router/claimants.ts
  src/main/common/router/defendants.ts
  src/main/common/router/routerFinder.ts
  src/main/modules/i18n/backend.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-918

#975 yarn audit known issues
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-975

#976 Fix/security nightly
  audit.json
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-976

#977 Fix/security nightly
  audit.json
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-977
