Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2021-03, with the labels that each got.

#1019 Update state.tf
  infrastructure/state.tf
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1019

#1028 Legal-rep-OWASP-error-fix
  src/main/app.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1028

#1032 fixed cves from rpe dashboard
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1032

#1040 Fix/cves
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1040

#1042 Updated the list of yarn audit issues
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1042
