Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2021-07, with the labels that each got.

#1125 env sync up
  Jenkinsfile_CNP
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1125

#1136 update cb tests
  bin/run-crossbrowser-tests.sh
  package.json
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1136

#1143 feature/ROC-9307-masterbot-pr upgrading nunjucks, node.js and config
  .nvmrc
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1143
