Repository hmcts/cmc-legal-rep-frontend, pull requests merged in 2022-02, with the labels that each got.

#1191 Delete package-lock.json - Yarn.lock should be used in all pipelines
  package-lock.json
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1191

#1206 CIV-1323 : updated yarn audit known issues log
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1206

#1215 CIV-1394 : updated yarn audit known issues
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-legal-frontend-pr-1215
